parameters:
    amf_open_vpn.server_management.class: AMF\OpenVpnBundle\EndPoint\ServerManagement
    
services:
    amf_open_vpn.server_management: 
        class: %amf_open_vpn.server_management.class%
        arguments: [%amf_open_vpn.servers%]

